### ISSUE TITLE
3rad - import both barcodes with pre-sorted fastq

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#280]
JStarret reported on gitter:
```
The source of the error (2017-11-02 10:22:08,736 pid=9857 [rawedit.py] ERROR error in run_cutadapt(): AttributeError('NoneType' object has no attribute 'replace') is that in the json file after step 1 both barcodes are not read when I use sorted fastqs, only the first barcode is read in the barcode list: "barcodes":{
"MY4221":"CTGCAACT", and for each sample the barcode reads null: "name":"MY4221",
"barcode":null, I manually added the correct barcode pair and was able to successfully run step2. This problem did not occur when ipyrad was used to demulitplex, only when sorted fastqs were used. 
```

**Comment by isaacovercast** [comment]
I'm having trouble reproducing this. The only calls to `replace` are in the parse_pair_results() command after cutadapt has been run, which indicates maybe it's returning some funny value.

**Comment by isaacovercast** [comment]
Yeah, i can see where something is getting wonky with multiplexed barcodes.

**Comment by isaacovercast** [comment]
I tested it and this works fine in v0.9.
